### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by tbrodbeck** [gonejack/hsize#2]
Great tool! Would be awesome it you could (optionally) remove the "{input} =>" part of the ouput!

e.g:
not `4472557 => 4.27MB`, but `4.27MB`

**Comment by gonejack** [comment]
Yes, it would be more unix style without =>, I will remove it.

**Comment by gonejack** [comment]
hi @tbrodbeck 

Try run this again `go get -u github.com/gonejack/hsize` and thanks for your feedback.

**Comment by tbrodbeck** [comment]
Thank you so much :)
